language: python

env:
  - FLASK_CONFIG=atmfinda.config.travis

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: python -m unittest